/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./index.html"
  ],
  theme: {
    extend: {
      colors: {
        background: '#0f131f',
        'on-background': '#dfe2f3',
        surface: '#0f131f',
        'on-surface': '#dfe2f3',
        'surface-dim': '#0f131f',
        'surface-bright': '#353946',
        'surface-container-lowest': '#0a0e1a',
        'surface-container-low': '#171b28',
        'surface-container': '#1b1f2c',
        'surface-container-high': '#262a37',
        'surface-container-highest': '#313442',
        'on-surface-variant': '#bacac7',
        'inverse-surface': '#dfe2f3',
        'inverse-on-surface': '#2c303d',
        'surface-tint': '#24ddd1',
        'surface-variant': '#313442',
        primary: '#47f1e4',
        'on-primary': '#003733',
        'primary-container': '#00d4c8',
        'on-primary-container': '#005651',
        'inverse-primary': '#006a64',
        'primary-fixed': '#54faed',
        'primary-fixed-dim': '#24ddd1',
        'on-primary-fixed': '#00201e',
        'on-primary-fixed-variant': '#00504b',
        secondary: '#d2bbff',
        'on-secondary': '#3f008e',
        'secondary-container': '#6001d1',
        'on-secondary-container': '#c9aeff',
        'secondary-fixed': '#eaddff',
        'secondary-fixed-dim': '#d2bbff',
        'on-secondary-fixed': '#25005a',
        'on-secondary-fixed-variant': '#5a00c6',
        tertiary: '#ffcfc0',
        'on-tertiary': '#5d1900',
        'tertiary-container': '#ffa88b',
        'on-tertiary-container': '#8d2a00',
        'tertiary-fixed': '#ffdbd0',
        'tertiary-fixed-dim': '#ffb59d',
        'on-tertiary-fixed': '#390c00',
        'on-tertiary-fixed-variant': '#832600',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        outline: '#849491',
        'outline-variant': '#3b4a48',
      },
      fontFamily: {
        heading: ['"Space Grotesk"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['"Space Grotesk"', 'monospace'],
      },
      fontSize: {
        'h1': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2': ['36px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'h3': ['28px', { lineHeight: '1.3', fontWeight: '600' }],
        'h4': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' }],
        'data-mono': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      spacing: {
        'unit': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '48px',
        'gutter': '20px',
        'margin': '32px',
      },
      borderRadius: {
        'sm': '0.125rem',
        DEFAULT: '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      boxShadow: {
        'neon-primary': '0 0 4px rgba(71, 241, 228, 0.5)',
        'neon-secondary': '0 0 4px rgba(210, 187, 255, 0.5)',
      },
      backgroundImage: {
        'mesh-navy-violet': 'radial-gradient(circle at top right, #3f008e 0%, #0f131f 40%), radial-gradient(circle at bottom left, #006a64 0%, #0f131f 40%)',
      },
    },
  },
  plugins: [],
}
